### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by liaoxuewei** [PoignardAzur/masonry-rs#36]
Follow the instructions to make a simple demo trainer, but there is a compilation error. Is there any information you can provide, thanks!

E:\MyProjects\rust-app>cargo build
    Updating `tuna` index
   Compiling masonry v0.1.2
error[E0609]: no field `app` on type `RefMut<'_, AppRootInner>`
   --> C:\Users\liaoxuewei\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\masonry-0.1.2\src\app_root.rs:217:19
    |
217 |             inner.app.quit();
    |                   ^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `masonry` due to previous error

**Comment by jinfar** [comment]
I have the same bug on

nightly-x86_64-pc-windows-msvc (default)
rustc 1.69.0-nightly (ef982929c 2023-01-27)

Compiling masonry v0.1.2
error[E0609]: no field `app` on type `RefMut<'_, AppRootInner>`
   --> C:\.cargo\registry\src\github.com-1ecc6299db9ec823\masonry-0.1.2\src\app_root.rs:217:19
    |
217 |             inner.app.quit();
    |                   ^^^ unknown field

**Comment by PoignardAzur** [comment]
Right. MacOS builds failed too.

I think this is because I renamed a field with rust-analyzer and it didn't propagate the rename to platforms I wasn't using. (Or maybe I did it by hand and forgot those.)

Should be fixed soon.

**Comment by PoignardAzur** [comment]
Can you run tests on windows with the latest commit?

I think I've fixed all the compilation problems, but for some reason `cargo test` fails in CI on Windows, and the error message isn't super informative.

To be specific, I'd like you to run these commands:

- `cargo.exe test` 
- `cargo.exe test --all-targets --no-default-features --features=svg,image,x11` 

both of them with env variable ` SKIP_RENDER_SNAPSHOTS=1` to avoid flaky snapshot tests.

**Comment by liaoxuewei** [comment]
I run cargo.exe test under src of [masonry-rs](https://github.com/PoignardAzur/masonry-rs)， is it right?

The result:
```

thread 'widget::spinner::tests::simple_spinner' panicked at 'Images are different', src\testing\harness.rs:591:17

---- widget::tests::lifecycle_basic::adding_child stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: src\widget\tests\snapshots\masonry__widget__tests__lifecycle_basic__adding_child.snap
Snapshot: adding_child
Source: E:\Opensource\__m\masonry-rs:53
──────────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

Expression: record_new_child
──────────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

-old snapshot
+new results
────────────┬─────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

    4     4 │     L(
    5     5 │         BuildFocusChain,
    6     6 │     ),
    7     7 │     Layout(
    8       │-        4.0W×18.0H,
          8 │+        4.0W×20.0H,
    9     9 │     ),
   10    10 │     L(
   11    11 │         Internal(
   12    12 │             ParentWindowOrigin,
────────────┴─────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'widget::tests::lifecycle_basic::adding_child' panicked at 'snapshot assertion for 'adding_child' failed in line 53', C:\Users\liaoxu
ewei\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\insta-1.18.2\src\runtime.rs:443:9

---- widget::split::tests::rows stdout ----
thread 'widget::split::tests::rows' panicked at 'Images are different', src\testing\harness.rs:591:17

---- widget::textbox::tests::simple_textbox stdout ----
thread 'widget::textbox::tests::simple_textbox' panicked at 'Images are different', src\testing\harness.rs:591:17

---- widget::textbox::tests::simple_textbox_placeholder stdout ----
thread 'widget::textbox::tests::simple_textbox_placeholder' panicked at 'Images are different', src\testing\harness.rs:591:17


failures:
    widget::align::tests::centered
    widget::align::tests::left
    widget::align::tests::right
    widget::button::tests::simple_button
    widget::checkbox::tests::simple_checkbox
    widget::flex::tests::flex_col_cross_axis_snapshots
    widget::flex::tests::flex_col_main_axis_snapshots
    widget::flex::tests::flex_row_cross_axis_snapshots
    widget::flex::tests::flex_row_main_axis_snapshots
    widget::label::tests::line_break_modes
    widget::label::tests::simple_label
    widget::label::tests::styled_label
    widget::portal::tests::button_list
    widget::scroll_bar::tests::horizontal_scrollbar
    widget::scroll_bar::tests::simple_scrollbar
    widget::sized_box::tests::empty_box
    widget::sized_box::tests::label_box_no_size
    widget::sized_box::tests::label_box_with_size
    widget::spinner::tests::simple_spinner
    widget::split::tests::columns
    widget::split::tests::rows
    widget::tests::invalidation::invalidate_union
    widget::tests::lifecycle_basic::adding_child
    widget::textbox::tests::simple_textbox
    widget::textbox::tests::simple_textbox_placeholder

test result: FAILED. 91 passed; 25 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.70s

error: test failed, to rerun pass `--lib`

```

**Comment by liaoxuewei** [comment]
After SET SKIP_RENDER_SNAPSHOTS=1,
run cargo.exe test
The result:

```
test widget::tests::lifecycle_focus::focus_status_change ... ok
test widget::tests::lifecycle_focus::resign_focus_on_disable ... ok
test widget::tests::lifecycle_focus::focus_updated_by_children_change ... ok
test widget::tests::safety_rails::allow_non_recurse_cursor_stashed ... ok
test widget::tests::lifecycle_focus::take_focus ... ok
test widget::tests::safety_rails::check_forget_children_changed - should panic ... ok
test widget::tests::safety_rails::check_forget_to_call_place_child - should panic ... ok
test widget::tests::safety_rails::check_forget_to_recurse_event - should panic ... ok
test widget::tests::safety_rails::check_forget_to_recurse_layout - should panic ... ok
test widget::tests::safety_rails::check_forget_to_recurse_lifecycle - should panic ... ok
test widget::tests::safety_rails::check_forget_to_recurse_widget_added - should panic ... ok
test widget::tests::safety_rails::check_layout_stashed - should panic ... ok
test widget::tests::safety_rails::check_forget_to_recurse_paint - should panic ... ok
test widget::tests::safety_rails::allow_non_recurse_stashed_paint ... ok
test widget::tests::safety_rails::check_paint_stashed - should panic ... ok
test widget::tests::status_change::get_mouse_events_while_active ... ok
test widget::tests::status_change::propagate_hot ... ok
test widget::tests::status_change::update_hot_on_mouse_leave ... ok
test widget::tests::status_change::update_hot_from_layout ... ok
test widget::tests::timers::basic_timer ... ok
test widget::textbox::tests::simple_textbox_placeholder ... ok
test widget::textbox::tests::simple_textbox ... ok
test widget::widget_ref::tests::downcast_ref ... ok
test widget::widget_ref::tests::downcast_ref_in_harness ... ok
test widget::textbox::tests::edit_textbox ... ok
stored new snapshot E:\Opensource\__m\masonry-rs\src\widget\tests\snapshots\masonry__widget__tests__lifecycle_basic__adding_child.snap.new
test widget::tests::lifecycle_basic::adding_child ... FAILED

failures:

---- widget::tests::invalidation::invalidate_union stdout ----
thread 'widget::tests::invalidation::invalidate_union' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(hresult 889900
12)', src\testing\harness.rs:279:14

---- widget::tests::lifecycle_basic::adding_child stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: src\widget\tests\snapshots\masonry__widget__tests__lifecycle_basic__adding_child.snap
Snapshot: adding_child
Source: E:\Opensource\__m\masonry-rs:53
──────────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

Expression: record_new_child
──────────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

-old snapshot
+new results
────────────┬─────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

    4     4 │     L(
    5     5 │         BuildFocusChain,
    6     6 │     ),
    7     7 │     Layout(
    8       │-        4.0W×18.0H,
          8 │+        4.0W×20.0H,
    9     9 │     ),
   10    10 │     L(
   11    11 │         Internal(
   12    12 │             ParentWindowOrigin,
────────────┴─────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────

To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'widget::tests::lifecycle_basic::adding_child' panicked at 'snapshot assertion for 'adding_child' failed in line 53', C:\Users\liaoxu
ewei\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\insta-1.18.2\src\runtime.rs:443:9


failures:
    widget::tests::invalidation::invalidate_union
    widget::tests::lifecycle_basic::adding_child

test result: FAILED. 114 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.05s

error: test failed, to rerun pass `--lib`

```

**Comment by PoignardAzur** [comment]
Alright, I don't have an immediate fix. I'll look into it soon.
